name: Mirror to CodeArts

on:
  push:
    branches: [main, nmw-custom]
  create:
  delete:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CODEARTS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # 替换 <CODEARTS_HOST> 为你的 CodeArts SSH 主机名
          # 例：codehub.cn-north-4.devcloud.extcloud.com.cn
          ssh-keyscan -H codehub.devcloud.cn-east-3.huaweicloud.com >> ~/.ssh/known_hosts

      - name: Clone fork bare
        run: |
          git clone --bare https://github.com/${{ github.repository }}.git repo
          cd repo
          git remote add codearts git@codehub.devcloud.cn-east-3.huaweicloud.com:14dbed93e27c4091967633086e9c75f0/nmw.git

      - name: Push main (mirror)
        run: |
          cd repo
          git push codearts main --tags --force-with-lease

      - name: Push nmw-custom (your dev branch)
        continue-on-error: true   # 该分支可能不存在（首次/未开发时），失败不影响主流程
        run: |
          cd repo
          git push codearts nmw-custom --force-with-lease
